/*
 * Copyright (c) 2009-2019 ARM Limited. All rights reserved.
 * 
 * SPDX-License-Identifier: Apache-2.0
 * 
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * @file     /home/jatsekku/svd2rust/SVDsamples/CH583SFR.h
 * @brief    CMSIS HeaderFile
 * @version  1.0
 * @date     02. July 2024
 * @note     Generated by SVDConv V3.3.35 on Tuesday, 02.07.2024 22:52:23
 *           from File 'ch58x.svd',
 */



/** @addtogroup WCH Ltd.
  * @{
  */


/** @addtogroup CH583SFR
  * @{
  */


#ifndef CH583SFR_H
#define CH583SFR_H

#ifdef __cplusplus
extern "C" {
#endif


/** @addtogroup Configuration_of_CMSIS
  * @{
  */



/* =========================================================================================================================== */
/* ================                                Interrupt Number Definition                                ================ */
/* =========================================================================================================================== */

typedef enum {
/* ==========================================  CH583SFR Specific Interrupt Numbers  ========================================== */
  TMR0_IRQn                 =  16,              /*!< 16 TMR0_IRQHandler                                                        */
  GPIO_A_IRQn               =  17,              /*!< 17 GPIO_IRQHandler                                                        */
  GPIO_B_IRQn               =  18,              /*!< 18 GPIO_IRQHandler                                                        */
  SPI0_IRQn                 =  19,              /*!< 19 SPI0_IRQHandler                                                        */
  BLEB_IRQn                 =  20,              /*!< 20 BB_IRQHandler                                                          */
  BLEL_IRQn                 =  21,              /*!< 21 LLE_IRQHandler                                                         */
  USB_IRQn                  =  22,              /*!< 22 USB_IRQHandler                                                         */
  USB2_IRQn                 =  23,              /*!< 23 USB2_IRQHandler                                                        */
  TMR1_IRQn                 =  24,              /*!< 24 TMR1_IRQHandler                                                        */
  TMR2_IRQn                 =  25,              /*!< 25 TMR2_IRQHandler                                                        */
  UART0_IRQn                =  26,              /*!< 26 UART0_IRQHandler                                                       */
  UART1_IRQn                =  27,              /*!< 27 UART1_IRQHandler                                                       */
  RTC_IRQn                  =  28,              /*!< 28 RTC_IRQHandler                                                         */
  ADC_IRQn                  =  29,              /*!< 29 ADC_IRQHandler                                                         */
  I2C_IRQn                  =  30,              /*!< 30 I2C_IRQHandler                                                         */
  PWMX_SPI1_IRQn            =  31,              /*!< 31 PWMX_SPI1_IRQHandler                                                   */
  TMR3_IRQn                 =  32,              /*!< 32 TMR3_IRQHandler                                                        */
  UART2_IRQn                =  33,              /*!< 33 UART2_IRQHandler                                                       */
  UART3_IRQn                =  34,              /*!< 34 UART3_IRQHandler                                                       */
  WDOG_BAT_IRQn             =  35               /*!< 35 WDT_IRQHandler                                                         */
} IRQn_Type;



/* =========================================================================================================================== */
/* ================                           Processor and Core Peripheral Section                           ================ */
/* =========================================================================================================================== */

/* =============================  Configuration of the undefined Processor and Core Peripherals  ============================= */
#define __UNDEF_REV                 0x0000U     /*!< undef Core Revision                                                       */
#define __NVIC_PRIO_BITS               0        /*!< Number of Bits used for Priority Levels                                   */
#define __Vendor_SysTickConfig         0        /*!< Set to 1 if different SysTick Config is used                              */


/** @} */ /* End of group Configuration_of_CMSIS */

#include "core_undef.h"                         /*!< undefined processor and core peripherals                                  */
#include "system_CH583SFR.h"                    /*!< CH583SFR System                                                           */

#ifndef __IM                                    /*!< Fallback for older CMSIS versions                                         */
  #define __IM   __I
#endif
#ifndef __OM                                    /*!< Fallback for older CMSIS versions                                         */
  #define __OM   __O
#endif
#ifndef __IOM                                   /*!< Fallback for older CMSIS versions                                         */
  #define __IOM  __IO
#endif


/* ========================================  Start of section using anonymous unions  ======================================== */
#if defined (__CC_ARM)
  #pragma push
  #pragma anon_unions
#elif defined (__ICCARM__)
  #pragma language=extended
#elif defined(__ARMCC_VERSION) && (__ARMCC_VERSION >= 6010050)
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wc11-extensions"
  #pragma clang diagnostic ignored "-Wreserved-id-macro"
  #pragma clang diagnostic ignored "-Wgnu-anonymous-struct"
  #pragma clang diagnostic ignored "-Wnested-anon-types"
#elif defined (__GNUC__)
  /* anonymous unions are enabled by default */
#elif defined (__TMS470__)
  /* anonymous unions are enabled by default */
#elif defined (__TASKING__)
  #pragma warning 586
#elif defined (__CSMC__)
  /* anonymous unions are enabled by default */
#else
  #warning Not supported compiler type
#endif


/* =========================================================================================================================== */
/* ================                            Device Specific Peripheral Section                             ================ */
/* =========================================================================================================================== */


/** @addtogroup Device_Peripheral_peripherals
  * @{
  */



/* =========================================================================================================================== */
/* ================                                            SYS                                            ================ */
/* =========================================================================================================================== */


/**
  * @brief System Control Register (SYS)
  */

typedef struct {                                /*!< (@ 0x40001000) SYS Structure                                              */
  __IM  uint32_t  RESERVED[2];
  __IOM uint16_t  R16_CLK_SYS_CFG;              /*!< (@ 0x00000008) RWA, system clock configuration, SAM                       */
  __IOM uint8_t   R8_HFCK_PWR_CTRL;             /*!< (@ 0x0000000A) RWA, high frequency clock module power control,
                                                                    SAM                                                        */
  __IM  uint8_t   RESERVED1;
  __IOM uint8_t   R8_SLP_CLK_OFF0;              /*!< (@ 0x0000000C) RWA, sleep clock off control byte 0, SAM                   */
  __IOM uint8_t   R8_SLP_CLK_OFF1;              /*!< (@ 0x0000000D) RWA, sleep clock off control byte 1, SAM                   */
  __IOM uint8_t   R8_SLP_WAKE_CTRL;             /*!< (@ 0x0000000E) RWA, wake control, SAM                                     */
  __IOM uint8_t   R8_SLP_POWER_CTRL;            /*!< (@ 0x0000000F) RWA, peripherals power down control, SAM                   */
  __IM  uint32_t  RESERVED2[2];
  __IOM uint16_t  R16_PIN_ALTERNATE;            /*!< (@ 0x00000018) RW, function pin alternate configuration                   */
  __IOM uint16_t  R16_PIN_ANALOG_IE;            /*!< (@ 0x0000001A) RW, analog pin enable and digital input disable            */
  __IM  uint32_t  RESERVED3;
  __IOM uint16_t  R16_POWER_PLAN;               /*!< (@ 0x00000020) RWA, power plan before sleep instruction, SAM              */
  __IOM uint8_t   R8_AUX_POWER_ADJ;             /*!< (@ 0x00000022) RWA, aux power adjust control, SAM                         */
  __IM  uint8_t   RESERVED4;
  __IOM uint8_t   R8_BAT_DET_CTRL;              /*!< (@ 0x00000024) RWA, battery voltage detector control, SAM                 */
  __IOM uint8_t   R8_BAT_DET_CFG;               /*!< (@ 0x00000025) RWA, battery voltage detector configuration,
                                                                    SAM                                                        */
  __IM  uint8_t   R8_BAT_STATUS;                /*!< (@ 0x00000026) RO, battery status                                         */
  __IM  uint8_t   RESERVED5;
  __IM  uint32_t  RESERVED6;
  __IOM uint16_t  R16_INT32K_TUNE;              /*!< (@ 0x0000002C) RWA, internal 32KHz oscillator tune control,
                                                                    SAM                                                        */
  __IOM uint8_t   R8_XT32K_TUNE;                /*!< (@ 0x0000002E) RWA, external 32KHz oscillator tune control,
                                                                    SAM                                                        */
  __IOM uint8_t   R8_CK32K_CONFIG;              /*!< (@ 0x0000002F) RWA, 32KHz oscillator configure                            */
  __IOM uint8_t   R8_RTC_FLAG_CTRL;             /*!< (@ 0x00000030) RW, RTC flag and clear control                             */
  __IOM uint8_t   R8_RTC_MODE_CTRL;             /*!< (@ 0x00000031) RWA, RTC mode control, SAM                                 */
  __IM  uint16_t  RESERVED7;
  __IOM uint32_t  R32_RTC_TRIG;                 /*!< (@ 0x00000034) RWA, RTC trigger value, SAM                                */
  __IM  uint16_t  R16_RTC_CNT_32K;              /*!< (@ 0x00000038) RO, RTC count based 32KHz                                  */
  __IM  uint16_t  R16_RTC_CNT_2S;               /*!< (@ 0x0000003A) RO, RTC count based 2 second                               */
  __IM  uint32_t  R32_RTC_CNT_DAY;              /*!< (@ 0x0000003C) RO, RTC count based one day, only low 14 bit               */
  __IOM uint8_t   R8_SAFE_ACCESS_SIG;           /*!< (@ 0x00000040) WO, safe accessing sign register, must write
                                                                    SAFE_ACCESS_SIG1 then SAFE_ACCESS_SIG2 to
                                                                    enter safe accessing mode                                  */
  __IM  uint8_t   R8_CHIP_ID;                   /*!< (@ 0x00000041) RF, chip ID register, always is ID_CH58*                   */
  __IM  uint8_t   R8_SAFE_ACCESS_ID;            /*!< (@ 0x00000042) RF, safe accessing ID register, always 0x0C                */
  __IOM uint8_t   R8_WDOG_COUNT;                /*!< (@ 0x00000043) RW, watch-dog count, count by clock frequency
                                                                    Fsys/131072                                                */
  __IM  uint8_t   R8_RESET_STATUS__R8_GLOB_ROM_CFG;/*!< (@ 0x00000044) RWA, reset status, SAM or flash ROM configuration       */
  __IM  uint8_t   R8_GLOB_CFG_INFO;             /*!< (@ 0x00000045) RO, global configuration information and status            */
  __IOM uint8_t   R8_RST_WDOG_CTRL;             /*!< (@ 0x00000046) RWA, reset and watch-dog control, SAM                      */
  __IOM uint8_t   R8_GLOB_RESET_KEEP;           /*!< (@ 0x00000047) RW, value keeper during global reset                       */
  __IM  uint16_t  RESERVED8;
  __IM  uint8_t   RESERVED9;
  __IOM uint8_t   R8_PLL_CONFIG;                /*!< (@ 0x0000004B) RWA, PLL configuration control, SAM                        */
  __IM  uint16_t  RESERVED10;
  __IOM uint8_t   R8_XT32M_TUNE;                /*!< (@ 0x0000004E) RWA, external 32MHz oscillator tune control,
                                                                    SAM                                                        */
  __IM  uint8_t   RESERVED11;
  __IM  uint16_t  R16_OSC_CAL_CNT;              /*!< (@ 0x00000050) RO, system clock count value for 32KHz multi-cycles        */
  __IM  uint8_t   R8_OSC_CAL_OV_CNT;            /*!< (@ 0x00000052) RO, oscillator frequency calibration overflow
                                                                    times                                                      */
  __IOM uint8_t   R8_OSC_CAL_CTRL;              /*!< (@ 0x00000053) RWA, oscillator frequency calibration control,
                                                                    SAM                                                        */
  __IOM uint8_t   R8_TKEY_COUNT;                /*!< (@ 0x00000054) RW, Touchkey charge and discharge count                    */
  __IM  uint8_t   RESERVED12;
  __IOM uint8_t   R8_TKEY_CONVERT;              /*!< (@ 0x00000056) RW, Touchkey convert start control                         */
  __IOM uint8_t   R8_TKEY_CFG;                  /*!< (@ 0x00000057) RW, Touchkey configure                                     */
  __IOM uint8_t   R8_ADC_CHANNEL;               /*!< (@ 0x00000058) RW, ADC input channel selection                            */
  __IOM uint8_t   R8_ADC_CFG;                   /*!< (@ 0x00000059) RW, ADC configure                                          */
  __IOM uint8_t   R8_ADC_CONVERT;               /*!< (@ 0x0000005A) RW, ADC convert control                                    */
  __IOM uint8_t   R8_TEM_SENSOR;                /*!< (@ 0x0000005B) RW, temperature sensor control                             */
  __IM  uint16_t  R16_ADC_DATA;                 /*!< (@ 0x0000005C) RO, ADC data                                               */
  __IM  uint8_t   R8_ADC_INT_FLAG;              /*!< (@ 0x0000005E) RO, ADC interrupt flag register                            */
  __IM  uint8_t   RESERVED13;
  __IOM uint8_t   R32_ADC_DMA_CTRL;             /*!< (@ 0x00000060) RO, ADC DMA control and status register                    */
  __IOM uint8_t   R8_ADC_CTRL_DMA;              /*!< (@ 0x00000061) RW, ADC DMA control                                        */
  __IOM uint8_t   R8_ADC_DMA_IF;                /*!< (@ 0x00000062) RO, ADC interrupt flag                                     */
  __IOM uint8_t   R8_ADC_AUTO_CYCLE;            /*!< (@ 0x00000063) RO, ADC interrupt flag                                     */
  __IM  uint16_t  R16_ADC_DMA_NOW;              /*!< (@ 0x00000064) RO, ADC DMA current address                                */
  __IM  uint16_t  RESERVED14;
  __IOM uint16_t  R16_ADC_DMA_BEG;              /*!< (@ 0x00000068) RW, ADC DMA begin address                                  */
  __IM  uint16_t  RESERVED15;
  __IOM uint16_t  R16_ADC_DMA_END;              /*!< (@ 0x0000006C) RW, ADC DMA end address                                    */
  __IM  uint16_t  RESERVED16;
  __IM  uint32_t  RESERVED17[8];
  __IOM uint16_t  R16_PA_INT_EN;                /*!< (@ 0x00000090) RW, GPIO PA interrupt enable                               */
  __IOM uint16_t  R16_PB_INT_EN;                /*!< (@ 0x00000092) RW, GPIO PB interrupt enable                               */
  __IOM uint16_t  R16_PA_INT_MODE;              /*!< (@ 0x00000094) RW, GPIO PA interrupt mode: 0=level action, 1=edge
                                                                    action                                                     */
  __IOM uint16_t  R16_PB_INT_MODE;              /*!< (@ 0x00000096) RW, GPIO PB interrupt mode: 0=level action, 1=edge
                                                                    action;RW, status for parallel slave read                  */
  __IM  uint32_t  RESERVED18;
  __IOM uint16_t  R16_PA_INT_IF;                /*!< (@ 0x0000009C) RW1, GPIO PA interrupt flag                                */
  __IOM uint16_t  R16_PB_INT_IF;                /*!< (@ 0x0000009E) RW1, GPIO PB interrupt flag                                */
  __IOM uint32_t  R32_PA_DIR;                   /*!< (@ 0x000000A0) RW, GPIO PA I/O direction: 0=in, 1=out                     */
  __IM  uint32_t  R32_PA_PIN;                   /*!< (@ 0x000000A4) RO, GPIO PA input                                          */
  __IOM uint32_t  R32_PA_OUT;                   /*!< (@ 0x000000A8) RW, GPIO PA output                                         */
  __IOM uint32_t  R32_PA_CLR;                   /*!< (@ 0x000000AC) WZ, GPIO PA clear output: 0=keep, 1=clear                  */
  __IOM uint32_t  R32_PA_PU;                    /*!< (@ 0x000000B0) RW, GPIO PA pullup resistance enable                       */
  __IOM uint32_t  R32_PA_PD_DRV;                /*!< (@ 0x000000B4) RW, PA pulldown for input or PA driving capability
                                                                    for output                                                 */
  __IM  uint32_t  RESERVED19[2];
  __IOM uint32_t  R32_PB_DIR;                   /*!< (@ 0x000000C0) RW, GPIO PB I/O direction: 0=in, 1=out                     */
  __IM  uint32_t  R32_PB_PIN;                   /*!< (@ 0x000000C4) RO, GPIO PB input                                          */
  __IOM uint32_t  R32_PB_OUT__R8_SLV_RD_DATA;   /*!< (@ 0x000000C8) RW, GPIO PB output;RW, data for parallel slave
                                                                    read                                                       */
  __IOM uint32_t  R32_PB_CLR;                   /*!< (@ 0x000000CC) WZ, GPIO PB clear output: 0=keep, 1=clear                  */
  __IOM uint32_t  R32_PB_PU;                    /*!< (@ 0x000000D0) RW, GPIO PB pullup resistance enable                       */
  __IOM uint32_t  R32_PB_PD_DRV;                /*!< (@ 0x000000D4) RW, PB pulldown for input or PB driving capability
                                                                    for output                                                 */
} SYS_Type;                                     /*!< Size = 216 (0xd8)                                                         */



/* =========================================================================================================================== */
/* ================                                           TMR0                                            ================ */
/* =========================================================================================================================== */


/**
  * @brief Timer0 register (TMR0)
  */

typedef struct {                                /*!< (@ 0x40002000) TMR0 Structure                                             */
  __IOM uint8_t   R8_TMR0_CTRL_MOD;             /*!< (@ 0x00000000) RW, TMR0 mode control                                      */
  __IM  uint8_t   RESERVED;
  __IOM uint8_t   R8_TMR0_INTER_EN;             /*!< (@ 0x00000002) RW, TMR0 interrupt enable                                  */
  __IM  uint8_t   RESERVED1;
  __IM  uint16_t  RESERVED2;
  __IOM uint8_t   R8_TMR0_INT_FLAG;             /*!< (@ 0x00000006) RW1, TMR0 interrupt flag                                   */
  __IM  uint8_t   R8_TMR0_FIFO_COUNT;           /*!< (@ 0x00000007) RO, TMR0 FIFO count status                                 */
  __IM  uint32_t  R32_TMR0_COUNT;               /*!< (@ 0x00000008) RO, TMR0 current count                                     */
  __IOM uint32_t  R32_TMR0_CNT_END;             /*!< (@ 0x0000000C) RW, TMR0 end count value, only low 26 bit                  */
  __IM  uint32_t  R32_TMR0_FIFO;                /*!< (@ 0x00000010) RO/WO, TMR0 FIFO register, only low 26 bit                 */
} TMR0_Type;                                    /*!< Size = 20 (0x14)                                                          */



/* =========================================================================================================================== */
/* ================                                           TMR1                                            ================ */
/* =========================================================================================================================== */


/**
  * @brief Timer1 register (TMR1)
  */

typedef struct {                                /*!< (@ 0x40002400) TMR1 Structure                                             */
  __IOM uint8_t   R8_TMR1_CTRL_MOD;             /*!< (@ 0x00000000) RW, TMR1 mode control                                      */
  __IOM uint8_t   R8_TMR1_CTRL_DMA;             /*!< (@ 0x00000001) RW, TMR1 DMA control                                       */
  __IOM uint8_t   R8_TMR1_INTER_EN;             /*!< (@ 0x00000002) RW, TMR1 interrupt enable                                  */
  __IM  uint8_t   RESERVED;
  __IM  uint16_t  RESERVED1;
  __IOM uint8_t   R8_TMR1_INT_FLAG;             /*!< (@ 0x00000006) RW1, TMR1 interrupt flag                                   */
  __IM  uint8_t   R8_TMR1_FIFO_COUNT;           /*!< (@ 0x00000007) RO, TMR1 FIFO count status                                 */
  __IM  uint32_t  R32_TMR1_COUNT;               /*!< (@ 0x00000008) RO, TMR1 current count                                     */
  __IOM uint32_t  R32_TMR1_CNT_END;             /*!< (@ 0x0000000C) RW, TMR1 end count value, only low 26 bit                  */
  __IM  uint32_t  R32_TMR1_FIFO;                /*!< (@ 0x00000010) RO, TMR1 FIFO register, only low 26 bit                    */
  __IM  uint16_t  R16_TMR1_DMA_NOW;             /*!< (@ 0x00000014) RO, TMR1 DMA current address                               */
  __IM  uint16_t  RESERVED2;
  __IOM uint16_t  R16_TMR1_DMA_BEG;             /*!< (@ 0x00000018) RW, TMR1 DMA begin address                                 */
  __IM  uint16_t  RESERVED3;
  __IOM uint16_t  R16_TMR1_DMA_END;             /*!< (@ 0x0000001C) RW, TMR1 DMA end address                                   */
  __IM  uint16_t  RESERVED4;
} TMR1_Type;                                    /*!< Size = 32 (0x20)                                                          */



/* =========================================================================================================================== */
/* ================                                           TMR2                                            ================ */
/* =========================================================================================================================== */


/**
  * @brief Timer2 register (TMR2)
  */

typedef struct {                                /*!< (@ 0x40002800) TMR2 Structure                                             */
  __IOM uint8_t   R8_TMR2_CTRL_MOD;             /*!< (@ 0x00000000) RW, TMR2 mode control                                      */
  __IOM uint8_t   R8_TMR2_CTRL_DMA;             /*!< (@ 0x00000001) RW, TMR2 DMA control                                       */
  __IOM uint8_t   R8_TMR2_INTER_EN;             /*!< (@ 0x00000002) RW, TMR2 interrupt enable                                  */
  __IM  uint8_t   RESERVED;
  __IM  uint16_t  RESERVED1;
  __IOM uint8_t   R8_TMR2_INT_FLAG;             /*!< (@ 0x00000006) RW1, TMR2 interrupt flag                                   */
  __IM  uint8_t   R8_TMR2_FIFO_COUNT;           /*!< (@ 0x00000007) RO, TMR2 FIFO count status                                 */
  __IM  uint32_t  R32_TMR2_COUNT;               /*!< (@ 0x00000008) RO, TMR2 current count                                     */
  __IOM uint32_t  R32_TMR2_CNT_END;             /*!< (@ 0x0000000C) RW, TMR2 end count value, only low 26 bit                  */
  __IOM uint32_t  R32_TMR2_FIFO;                /*!< (@ 0x00000010) RO, TMR2 FIFO register, only low 26 bit                    */
  __IM  uint16_t  R16_TMR2_DMA_NOW;             /*!< (@ 0x00000014) RO, TMR2 DMA current address                               */
  __IM  uint16_t  RESERVED2;
  __IOM uint16_t  R16_TMR2_DMA_BEG;             /*!< (@ 0x00000018) RW, TMR2 DMA begin address                                 */
  __IM  uint16_t  RESERVED3;
  __IOM uint16_t  R16_TMR2_DMA_END;             /*!< (@ 0x0000001C) RW, TMR2 DMA end address                                   */
  __IM  uint16_t  RESERVED4;
} TMR2_Type;                                    /*!< Size = 32 (0x20)                                                          */



/* =========================================================================================================================== */
/* ================                                           TMR3                                            ================ */
/* =========================================================================================================================== */


/**
  * @brief Timer3 register (TMR3)
  */

typedef struct {                                /*!< (@ 0x40002C00) TMR3 Structure                                             */
  __IOM uint8_t   R8_TMR3_CTRL_MOD;             /*!< (@ 0x00000000) RW, TMR3 mode control                                      */
  __IM  uint8_t   RESERVED;
  __IOM uint8_t   R8_TMR3_INTER_EN;             /*!< (@ 0x00000002) RW, TMR3 interrupt enable                                  */
  __IM  uint8_t   RESERVED1;
  __IM  uint16_t  RESERVED2;
  __IOM uint8_t   R8_TMR3_INT_FLAG;             /*!< (@ 0x00000006) RW1, TMR3 interrupt flag                                   */
  __IM  uint8_t   R8_TMR3_FIFO_COUNT;           /*!< (@ 0x00000007) RO, TMR3 FIFO count status                                 */
  __IM  uint32_t  R32_TMR3_COUNT;               /*!< (@ 0x00000008) RO, TMR3 current count                                     */
  __IOM uint32_t  R32_TMR3_CNT_END;             /*!< (@ 0x0000000C) RW, TMR3 end count value, only low 26 bit                  */
  __IOM uint32_t  R32_TMR3_FIFO;                /*!< (@ 0x00000010) RO/WO, TMR3 FIFO register, only low 26 bit                 */
} TMR3_Type;                                    /*!< Size = 20 (0x14)                                                          */



/* =========================================================================================================================== */
/* ================                                           UART0                                           ================ */
/* =========================================================================================================================== */


/**
  * @brief UART0 register (UART0)
  */

typedef struct {                                /*!< (@ 0x40003000) UART0 Structure                                            */
  __IOM uint8_t   R8_UART0_MCR;                 /*!< (@ 0x00000000) RW, UART0 modem control                                    */
  __IOM uint8_t   R8_UART0_IER;                 /*!< (@ 0x00000001) RW, UART0 interrupt enable                                 */
  __IOM uint8_t   R8_UART0_FCR;                 /*!< (@ 0x00000002) RW, UART0 FIFO control                                     */
  __IOM uint8_t   R8_UART0_LCR;                 /*!< (@ 0x00000003) RW, UART0 line control                                     */
  __IM  uint8_t   R8_UART0_IIR;                 /*!< (@ 0x00000004) RO, UART0 interrupt identification                         */
  __IM  uint8_t   R8_UART0_LSR;                 /*!< (@ 0x00000005) RO, UART0 line status                                      */
  __IM  uint8_t   R8_UART0_MSR;                 /*!< (@ 0x00000006) RO, UART0 modem status                                     */
  __IM  uint8_t   RESERVED;
  
  union {
    __IM  uint8_t R8_UART0_RBR;                 /*!< (@ 0x00000008) RO, UART0 receiver buffer, receiving byte                  */
    __OM  uint8_t R8_UART0_THR;                 /*!< (@ 0x00000008) WO, UART0 transmitter holding, transmittal byte            */
  };
  __IM  uint8_t   RESERVED1;
  __IM  uint8_t   R8_UART0_RFC;                 /*!< (@ 0x0000000A) RO, UART0 receiver FIFO count                              */
  __IM  uint8_t   R8_UART0_TFC;                 /*!< (@ 0x0000000B) RO, UART0 transmitter FIFO count                           */
  __IOM uint16_t  R16_UART0_DL;                 /*!< (@ 0x0000000C) RW, UART0 divisor latch                                    */
  __IOM uint8_t   R8_UART0_DIV;                 /*!< (@ 0x0000000E) RW, UART0 pre-divisor latch byte, only low 7
                                                                    bit, from 1 to 0/128                                       */
  __IOM uint8_t   R8_UART0_ADR;                 /*!< (@ 0x0000000F) RW, UART0 slave address: 0xFF=disable, other=enable        */
} UART0_Type;                                   /*!< Size = 16 (0x10)                                                          */



/* =========================================================================================================================== */
/* ================                                           UART1                                           ================ */
/* =========================================================================================================================== */


/**
  * @brief UART1 register (UART1)
  */

typedef struct {                                /*!< (@ 0x40003400) UART1 Structure                                            */
  __IOM uint8_t   R8_UART1_MCR;                 /*!< (@ 0x00000000) RW, UART1 modem control                                    */
  __IOM uint8_t   R8_UART1_IER;                 /*!< (@ 0x00000001) RW, UART1 interrupt enable                                 */
  __IOM uint8_t   R8_UART1_FCR;                 /*!< (@ 0x00000002) RW, UART1 FIFO control                                     */
  __IOM uint8_t   R8_UART1_LCR;                 /*!< (@ 0x00000003) RW, UART1 line control                                     */
  __IM  uint8_t   R8_UART1_IIR;                 /*!< (@ 0x00000004) RO, UART1 interrupt identification                         */
  __IM  uint8_t   R8_UART1_LSR;                 /*!< (@ 0x00000005) RO, UART1 line status                                      */
  __IM  uint16_t  RESERVED;
  
  union {
    __IM  uint8_t R8_UART1_RBR;                 /*!< (@ 0x00000008) RO, UART1 receiver buffer, receiving byte                  */
    __OM  uint8_t R8_UART1_THR;                 /*!< (@ 0x00000008) WO, UART1 transmitter holding, transmittal byte            */
  };
  __IM  uint8_t   RESERVED1;
  __IM  uint8_t   R8_UART1_RFC;                 /*!< (@ 0x0000000A) RO, UART1 receiver FIFO count                              */
  __IM  uint8_t   R8_UART1_TFC;                 /*!< (@ 0x0000000B) RO, UART1 transmitter FIFO count                           */
  __IOM uint16_t  R16_UART1_DL;                 /*!< (@ 0x0000000C) RW, UART1 divisor latch                                    */
  __IOM uint8_t   R8_UART1_DIV;                 /*!< (@ 0x0000000E) RW, UART1 pre-divisor latch byte, only low 7
                                                                    bit, from 1 to 128                                         */
  __IM  uint8_t   RESERVED2;
  __IM  uint16_t  RESERVED3;
} UART1_Type;                                   /*!< Size = 18 (0x12)                                                          */



/* =========================================================================================================================== */
/* ================                                           UART2                                           ================ */
/* =========================================================================================================================== */


/**
  * @brief UART2 register (UART2)
  */

typedef struct {                                /*!< (@ 0x40003800) UART2 Structure                                            */
  __IOM uint8_t   R8_UART2_MCR;                 /*!< (@ 0x00000000) RW, UART2 modem control                                    */
  __IOM uint8_t   R8_UART2_IER;                 /*!< (@ 0x00000001) RW, UART2 interrupt enable                                 */
  __IOM uint8_t   R8_UART2_FCR;                 /*!< (@ 0x00000002) RW, UART2 FIFO control                                     */
  __IOM uint8_t   R8_UART2_LCR;                 /*!< (@ 0x00000003) RW, UART2 line control                                     */
  __IM  uint8_t   R8_UART2_IIR;                 /*!< (@ 0x00000004) RO, UART2 interrupt identification                         */
  __IM  uint8_t   R8_UART2_LSR;                 /*!< (@ 0x00000005) RO, UART2 line status                                      */
  __IM  uint16_t  RESERVED;
  
  union {
    __IM  uint8_t R8_UART2_RBR;                 /*!< (@ 0x00000008) RO, UART2 receiver buffer, receiving byte                  */
    __OM  uint8_t R8_UART2_THR;                 /*!< (@ 0x00000008) WO, UART2 transmitter holding, transmittal byte            */
  };
  __IM  uint8_t   RESERVED1;
  __IM  uint8_t   R8_UART2_RFC;                 /*!< (@ 0x0000000A) RO, UART2 receiver FIFO count                              */
  __IM  uint8_t   R8_UART2_TFC;                 /*!< (@ 0x0000000B) RO, UART2 transmitter FIFO count                           */
  __IOM uint16_t  R16_UART2_DL;                 /*!< (@ 0x0000000C) RW, UART2 divisor latch                                    */
  __IOM uint8_t   R8_UART2_DIV;                 /*!< (@ 0x0000000E) RW, UART2 pre-divisor latch byte, only low 7
                                                                    bit, from 1 to 128                                         */
  __IM  uint8_t   RESERVED2;
  __IM  uint16_t  RESERVED3;
} UART2_Type;                                   /*!< Size = 18 (0x12)                                                          */



/* =========================================================================================================================== */
/* ================                                           UART3                                           ================ */
/* =========================================================================================================================== */


/**
  * @brief UART3 register (UART3)
  */

typedef struct {                                /*!< (@ 0x40003C00) UART3 Structure                                            */
  __IOM uint8_t   R8_UART3_MCR;                 /*!< (@ 0x00000000) RW, UART3 modem control                                    */
  __IOM uint8_t   R8_UART3_IER;                 /*!< (@ 0x00000001) RW, UART3 interrupt enable                                 */
  __IOM uint8_t   R8_UART3_FCR;                 /*!< (@ 0x00000002) RW, UART3 FIFO control                                     */
  __IOM uint8_t   R8_UART3_LCR;                 /*!< (@ 0x00000003) RW, UART3 line control                                     */
  __IM  uint8_t   R8_UART3_IIR;                 /*!< (@ 0x00000004) RO, UART3 interrupt identification                         */
  __IM  uint8_t   R8_UART3_LSR;                 /*!< (@ 0x00000005) RO, UART3 line status                                      */
  __IM  uint16_t  RESERVED;
  
  union {
    __IM  uint8_t R8_UART3_RBR;                 /*!< (@ 0x00000008) RO, UART3 receiver buffer, receiving byte                  */
    __OM  uint8_t R8_UART3_THR;                 /*!< (@ 0x00000008) WO, UART3 transmitter holding, transmittal byte            */
  };
  __IM  uint8_t   RESERVED1;
  __IM  uint8_t   R8_UART3_RFC;                 /*!< (@ 0x0000000A) RO, UART3 receiver FIFO count                              */
  __IM  uint8_t   R8_UART3_TFC;                 /*!< (@ 0x0000000B) RO, UART3 transmitter FIFO count                           */
  __IOM uint16_t  R16_UART3_DL;                 /*!< (@ 0x0000000C) RW, UART3 divisor latch                                    */
  __IOM uint8_t   R8_UART3_DIV;                 /*!< (@ 0x0000000E) RW, UART3 pre-divisor latch byte, only low 7
                                                                    bit, from 1 to 128                                         */
  __IM  uint8_t   RESERVED2;
  __IM  uint16_t  RESERVED3;
} UART3_Type;                                   /*!< Size = 18 (0x12)                                                          */



/* =========================================================================================================================== */
/* ================                                           SPI0                                            ================ */
/* =========================================================================================================================== */


/**
  * @brief SPI0 register (SPI0)
  */

typedef struct {                                /*!< (@ 0x40004000) SPI0 Structure                                             */
  __IOM uint8_t   R8_SPI0_CTRL_MOD;             /*!< (@ 0x00000000) RW, SPI0 mode control                                      */
  __IOM uint8_t   R8_SPI0_CTRL_CFG;             /*!< (@ 0x00000001) RW, SPI0 configuration control                             */
  __IOM uint8_t   R8_SPI0_INTER_EN;             /*!< (@ 0x00000002) RW, SPI0 interrupt enable                                  */
  __IOM uint8_t   R8_SPI0_CLOCK_DIV__R8_SPI0_SLAVE_PRE;/*!< (@ 0x00000003) RW, SPI0 master clock divisor;RW, SPI0 slave
                                                                    preset value                                               */
  __IOM uint8_t   R8_SPI0_BUFFER;               /*!< (@ 0x00000004) RW, SPI0 data buffer                                       */
  __IM  uint8_t   R8_SPI0_RUN_FLAG;             /*!< (@ 0x00000005) RO, SPI0 work flag                                         */
  __IOM uint8_t   R8_SPI0_INT_FLAG;             /*!< (@ 0x00000006) RW1, SPI0 interrupt flag                                   */
  __IM  uint8_t   R8_SPI0_FIFO_COUNT;           /*!< (@ 0x00000007) RO, SPI0 FIFO count status                                 */
  __IM  uint16_t  RESERVED[2];
  __IOM uint16_t  R16_SPI0_TOTAL_CNT;           /*!< (@ 0x0000000C) RW, SPI0 total byte count, only low 12 bit                 */
  __IM  uint16_t  RESERVED1;
  __IOM uint8_t   R8_SPI0_FIFO;                 /*!< (@ 0x00000010) RO/WO, SPI0 FIFO register                                  */
  __IM  uint8_t   RESERVED2[2];
  __IM  uint8_t   R8_SPI0_FIFO_COUNT1;          /*!< (@ 0x00000013) RO, SPI0 FIFO count status                                 */
  __IOM uint16_t  R16_SPI0_DMA_NOW;             /*!< (@ 0x00000014) RW, SPI0 DMA current address                               */
  __IM  uint16_t  RESERVED3;
  __IOM uint16_t  R16_SPI0_DMA_BEG;             /*!< (@ 0x00000018) RW, SPI0 DMA begin address                                 */
  __IM  uint16_t  RESERVED4;
  __IOM uint16_t  R16_SPI0_DMA_END;             /*!< (@ 0x0000001C) RW, SPI0 DMA end address                                   */
} SPI0_Type;                                    /*!< Size = 30 (0x1e)                                                          */



/* =========================================================================================================================== */
/* ================                                           SPI1                                            ================ */
/* =========================================================================================================================== */


/**
  * @brief SPI1 register (SPI1)
  */

typedef struct {                                /*!< (@ 0x40004400) SPI1 Structure                                             */
  __IOM uint8_t   R8_SPI1_CTRL_MOD;             /*!< (@ 0x00000000) RW, SPI1 mode control                                      */
  __IOM uint8_t   R8_SPI1_CTRL_CFG;             /*!< (@ 0x00000001) RW, SPI1 configuration control                             */
  __IOM uint8_t   R8_SPI1_INTER_EN;             /*!< (@ 0x00000002) RW, SPI1 interrupt enable                                  */
  __IOM uint8_t   R8_SPI1_CLOCK_DIV;            /*!< (@ 0x00000003) RW, SPI1 master clock divisor;                             */
  __IOM uint8_t   R8_SPI1_BUFFER;               /*!< (@ 0x00000004) RW, SPI1 data buffer                                       */
  __IM  uint8_t   R8_SPI1_RUN_FLAG;             /*!< (@ 0x00000005) RO, SPI1 work flag                                         */
  __IOM uint8_t   R8_SPI1_INT_FLAG;             /*!< (@ 0x00000006) RW1, SPI1 interrupt flag                                   */
  __IM  uint8_t   R8_SPI1_FIFO_COUNT;           /*!< (@ 0x00000007) RO, SPI1 FIFO count status                                 */
  __IM  uint16_t  RESERVED[2];
  __IOM uint16_t  R16_SPI1_TOTAL_CNT;           /*!< (@ 0x0000000C) RW, SPI1 total byte count, only low 12 bit                 */
  __IM  uint16_t  RESERVED1;
  __IOM uint8_t   R8_SPI1_FIFO;                 /*!< (@ 0x00000010) RO/WO, SPI1 FIFO register                                  */
  __IM  uint8_t   RESERVED2[2];
  __IM  uint8_t   R8_SPI1_FIFO_COUNT1;          /*!< (@ 0x00000013) RO, SPI1 FIFO count status                                 */
} SPI1_Type;                                    /*!< Size = 20 (0x14)                                                          */



/* =========================================================================================================================== */
/* ================                                            I2C                                            ================ */
/* =========================================================================================================================== */


/**
  * @brief I2C register (I2C)
  */

typedef struct {                                /*!< (@ 0x40004800) I2C Structure                                              */
  __IOM uint16_t  R16_I2C_CTRL1;                /*!< (@ 0x00000000) RW, I2C control 1                                          */
  __IM  uint16_t  RESERVED;
  __IOM uint16_t  R16_I2C_CTRL2;                /*!< (@ 0x00000004) RW, I2C control 2                                          */
  __IM  uint16_t  RESERVED1;
  __IOM uint16_t  R16_I2C_OADDR1;               /*!< (@ 0x00000008) RW, I2C own address register 1                             */
  __IM  uint16_t  RESERVED2;
  __IOM uint16_t  R16_I2C_OADDR2;               /*!< (@ 0x0000000C) RW, I2C own address register 2                             */
  __IM  uint16_t  RESERVED3;
  __IOM uint16_t  R16_I2C_DATAR;                /*!< (@ 0x00000010) RW, I2C data register                                      */
  __IM  uint16_t  RESERVED4;
  __IM  uint16_t  R16_I2C_STAR1;                /*!< (@ 0x00000014) R0, I2C stauts register 1                                  */
  __IM  uint16_t  RESERVED5;
  
  union {
    __IM  uint16_t R16_I2C_STAR2;               /*!< (@ 0x00000018) R0, I2C status register 2                                  */
    
    struct {
      __IM  uint8_t RESERVED6;
      __IM  uint8_t R8_I2C_PEC;                 /*!< (@ 0x00000019) R0, I2C Packet error checking register                     */
    };
  };
  __IM  uint16_t  RESERVED7;
  __IOM uint16_t  R16_I2C_CKCFGR;               /*!< (@ 0x0000001C) RW, I2C clock control register                             */
  __IM  uint16_t  RESERVED8;
  __IOM uint16_t  R16_I2C_RTR;                  /*!< (@ 0x00000020) RW, I2C trise register                                     */
} I2C_Type;                                     /*!< Size = 34 (0x22)                                                          */



/* =========================================================================================================================== */
/* ================                                           PWMx                                            ================ */
/* =========================================================================================================================== */


/**
  * @brief PWMx register (PWMx)
  */

typedef struct {                                /*!< (@ 0x40005000) PWMx Structure                                             */
  __IOM uint8_t   R8_PWM_OUT_EN;                /*!< (@ 0x00000000) RW, PWM output enable control                              */
  __IOM uint8_t   R8_PWM_POLAR;                 /*!< (@ 0x00000001) RW, PWM output polarity control                            */
  __IOM uint8_t   R8_PWM_CONFIG;                /*!< (@ 0x00000002) RW, PWM configuration                                      */
  __IOM uint8_t   R8_PWM_CLOCK_DIV;             /*!< (@ 0x00000003) RW, PWM clock divisor                                      */
  __IOM uint8_t   R8_PWM4_DATA;                 /*!< (@ 0x00000004) RW, PWM4 data holding                                      */
  __IOM uint8_t   R8_PWM5_DATA;                 /*!< (@ 0x00000005) RW, PWM5 data holding                                      */
  __IOM uint8_t   R8_PWM6_DATA;                 /*!< (@ 0x00000006) RW, PWM6 data holding                                      */
  __IOM uint8_t   R8_PWM7_DATA;                 /*!< (@ 0x00000007) RW, PWM7 data holding                                      */
  __IOM uint8_t   R8_PWM8_DATA;                 /*!< (@ 0x00000008) RW, PWM8 data holding                                      */
  __IOM uint8_t   R8_PWM9_DATA;                 /*!< (@ 0x00000009) RW, PWM9 data holding                                      */
  __IOM uint8_t   R8_PWM10_DATA;                /*!< (@ 0x0000000A) RW, PWM10 data holding                                     */
  __IOM uint8_t   R8_PWM11_DATA;                /*!< (@ 0x0000000B) RW, PWM11 data holding                                     */
  __IOM uint8_t   R8_PWM_INT_CTRL;              /*!< (@ 0x0000000C) RW, PWM interrupt control                                  */
} PWMx_Type;                                    /*!< Size = 13 (0xd)                                                           */



/* =========================================================================================================================== */
/* ================                                            USB                                            ================ */
/* =========================================================================================================================== */


/**
  * @brief USB register (USB)
  */

typedef struct {                                /*!< (@ 0x40008000) USB Structure                                              */
  __IOM uint8_t   R8_USB_CTRL;                  /*!< (@ 0x00000000) USB base control                                           */
  __IOM uint8_t   R8_UDEV_CTRL__R8_UHOST_CTRL;  /*!< (@ 0x00000001) USB device physical prot control                           */
  __IOM uint8_t   R8_USB_INT_EN;                /*!< (@ 0x00000002) USB interrupt enable                                       */
  __IOM uint8_t   R8_USB_DEV_AD;                /*!< (@ 0x00000003) USB device address                                         */
  __IM  uint8_t   RESERVED;
  __IM  uint8_t   R8_USB_MIS_ST;                /*!< (@ 0x00000005) USB miscellaneous status                                   */
  __IOM uint8_t   R8_USB_INT_FG;                /*!< (@ 0x00000006) USB interrupt flag                                         */
  __IM  uint8_t   R8_USB_INT_ST;                /*!< (@ 0x00000007) USB interrupt status                                       */
  __IM  uint8_t   R8_USB_RX_LEN;                /*!< (@ 0x00000008) USB receiving length                                       */
  __IM  uint8_t   RESERVED1;
  __IM  uint16_t  RESERVED2;
  __IOM uint8_t   R8_UEP4_1_MOD;                /*!< (@ 0x0000000C) endpoint 4/1 mode                                          */
  __IOM uint8_t   R8_UEP2_3_MOD__R8_UH_EP_MOD;  /*!< (@ 0x0000000D) endpoint 2_3 mode;host endpoint mode                       */
  __IOM uint8_t   R8_UEP567_MOD;                /*!< (@ 0x0000000E) endpoint 5/6/7 mode                                        */
  __IM  uint8_t   RESERVED3;
  __IOM uint16_t  R16_UEP0_DMA;                 /*!< (@ 0x00000010) endpoint 0 DMA buffer address                              */
  __IM  uint16_t  RESERVED4;
  __IOM uint16_t  R16_UEP1_DMA;                 /*!< (@ 0x00000014) endpoint 1 DMA buffer address                              */
  __IM  uint16_t  RESERVED5;
  __IOM uint16_t  R16_UEP2_DMA__R16_UH_RX_DMA;  /*!< (@ 0x00000018) endpoint 2 DMA buffer address;host rx endpoint
                                                                    buffer high address                                        */
  __IM  uint16_t  RESERVED6;
  __IOM uint16_t  R16_UEP3_DMA__R16_UH_TX_DMA;  /*!< (@ 0x0000001C) endpoint 3 DMA buffer address;host tx endpoint
                                                                    buffer high address                                        */
  __IM  uint16_t  RESERVED7;
  __IOM uint8_t   R8_UEP0_T_LEN;                /*!< (@ 0x00000020) endpoint 0 transmittal length                              */
  __IM  uint8_t   RESERVED8;
  __IOM uint8_t   R8_UEP0_CTRL;                 /*!< (@ 0x00000022) endpoint 0 control                                         */
  __IM  uint8_t   RESERVED9;
  __IOM uint8_t   R8_UEP1_T_LEN;                /*!< (@ 0x00000024) endpoint 1 transmittal length                              */
  __IM  uint8_t   RESERVED10;
  __IOM uint8_t   R8_UEP1_CTRL__R8_UH_SETUP;    /*!< (@ 0x00000026) endpoint 1 control;host aux setup                          */
  __IM  uint8_t   RESERVED11;
  __IOM uint8_t   R8_UEP2_T_LEN_R8_UH_EP_PID;   /*!< (@ 0x00000028) endpoint 2 transmittal length;host endpoint and
                                                                    PID                                                        */
  __IM  uint8_t   RESERVED12;
  __IOM uint8_t   R8_UEP2_CTRL_R8_UH_RX_CTRL;   /*!< (@ 0x0000002A) endpoint 2 control;host receiver endpoint control          */
  __IM  uint8_t   RESERVED13;
  __IOM uint8_t   R8_UEP3_T_LEN__R8_UH_TX_LEN;  /*!< (@ 0x0000002C) endpoint 3 transmittal length;host transmittal
                                                                    endpoint transmittal length                                */
  __IM  uint8_t   RESERVED14;
  __IOM uint8_t   R8_UEP3_CTRL__R8_UH_TX_CTRL;  /*!< (@ 0x0000002E) endpoint 3 control;host transmittal endpoint
                                                                    control                                                    */
  __IM  uint8_t   RESERVED15;
  __IOM uint8_t   R8_UEP4_T_LEN;                /*!< (@ 0x00000030) endpoint 4 transmittal length                              */
  __IM  uint8_t   RESERVED16;
  __IOM uint8_t   R8_UEP4_CTRL;                 /*!< (@ 0x00000032) endpoint 4 control                                         */
  __IM  uint8_t   RESERVED17;
  __IM  uint16_t  RESERVED18[16];
  __IOM uint16_t  R16_UEP5_DMA;                 /*!< (@ 0x00000054) endpoint 5 DMA buffer address                              */
  __IM  uint16_t  RESERVED19;
  __IOM uint16_t  R16_UEP6_DMA;                 /*!< (@ 0x00000058) endpoint 6 DMA buffer address                              */
  __IM  uint16_t  RESERVED20;
  __IOM uint16_t  R16_UEP7_DMA;                 /*!< (@ 0x0000005C) endpoint 7 DMA buffer address                              */
  __IM  uint16_t  RESERVED21[3];
  __IOM uint8_t   R8_UEP5_T_LEN;                /*!< (@ 0x00000064) endpoint 5 transmittal length                              */
  __IM  uint8_t   RESERVED22;
  __IOM uint8_t   R8_UEP5_CTRL;                 /*!< (@ 0x00000066) endpoint 5 control                                         */
  __IM  uint8_t   RESERVED23;
  __IOM uint8_t   R8_UEP6_T_LEN;                /*!< (@ 0x00000068) endpoint 6 transmittal length                              */
  __IM  uint8_t   RESERVED24;
  __IOM uint8_t   R8_UEP6_CTRL;                 /*!< (@ 0x0000006A) endpoint 6 control                                         */
  __IM  uint8_t   RESERVED25;
  __IOM uint8_t   R8_UEP7_T_LEN;                /*!< (@ 0x0000006C) endpoint 7 transmittal length                              */
  __IM  uint8_t   RESERVED26;
  __IOM uint8_t   R8_UEP7_CTRL;                 /*!< (@ 0x0000006E) endpoint 7 control                                         */
  __IM  uint8_t   RESERVED27;
  __IM  uint16_t  RESERVED28;
} USB_Type;                                     /*!< Size = 114 (0x72)                                                         */



/* =========================================================================================================================== */
/* ================                                           USB2                                            ================ */
/* =========================================================================================================================== */


/**
  * @brief USB2 register (USB2)
  */

typedef struct {                                /*!< (@ 0x40008400) USB2 Structure                                             */
  __IOM uint8_t   R8_USB2_CTRL;                 /*!< (@ 0x00000000) USB2 base control                                          */
  __IOM uint8_t   R8_U2DEV_CTRL__R8_U2HOST_CTRL;/*!< (@ 0x00000001) USB2 device physical prot control                          */
  __IOM uint8_t   R8_USB2_INT_EN;               /*!< (@ 0x00000002) USB2 interrupt enable                                      */
  __IOM uint8_t   R8_USB2_DEV_AD;               /*!< (@ 0x00000003) USB2 device address                                        */
  __IM  uint8_t   RESERVED;
  __IM  uint8_t   R8_USB2_MIS_ST;               /*!< (@ 0x00000005) USB2 miscellaneous status                                  */
  __IOM uint8_t   R8_USB2_INT_FG;               /*!< (@ 0x00000006) USB2 interrupt flag                                        */
  __IM  uint8_t   R8_USB2_INT_ST;               /*!< (@ 0x00000007) USB2 interrupt status                                      */
  __IM  uint8_t   R8_USB2_RX_LEN;               /*!< (@ 0x00000008) USB2 receiving length                                      */
  __IM  uint8_t   RESERVED1;
  __IM  uint16_t  RESERVED2;
  __IOM uint8_t   R8_U2EP4_1_MOD;               /*!< (@ 0x0000000C) endpoint 4/1 mode                                          */
  __IOM uint8_t   R8_U2EP2_3_MOD__R8_U2H_EP_MOD;/*!< (@ 0x0000000D) endpoint 2_3 mode;host endpoint mode                       */
  __IOM uint8_t   R8_U2EP567_MOD;               /*!< (@ 0x0000000E) USB2 endpoint 5/6/7 mode                                   */
  __IM  uint8_t   RESERVED3;
  __IOM uint16_t  R16_U2EP0_DMA;                /*!< (@ 0x00000010) endpoint 0 DMA buffer address                              */
  __IM  uint16_t  RESERVED4;
  __IOM uint16_t  R16_U2EP1_DMA;                /*!< (@ 0x00000014) USB2 endpoint 1 DMA buffer address                         */
  __IM  uint16_t  RESERVED5;
  __IOM uint16_t  R16_U2EP2_DMA__R16_U2H_RX_DMA;/*!< (@ 0x00000018) USB2 endpoint 2 DMA buffer address;host rx endpoint
                                                                    buffer high address                                        */
  __IM  uint16_t  RESERVED6;
  __IOM uint16_t  R16_U2EP3_DMA__R16_U2H_TX_DMA;/*!< (@ 0x0000001C) USB2 endpoint 3 DMA buffer address;host tx endpoint
                                                                    buffer high address                                        */
  __IM  uint16_t  RESERVED7;
  __IOM uint8_t   R8_U2EP0_T_LEN;               /*!< (@ 0x00000020) USB2 endpoint 0 transmittal length                         */
  __IM  uint8_t   RESERVED8;
  __IOM uint8_t   R8_U2EP0_CTRL;                /*!< (@ 0x00000022) USB2 endpoint 0 control                                    */
  __IM  uint8_t   RESERVED9;
  __IOM uint8_t   R8_U2EP1_T_LEN;               /*!< (@ 0x00000024) USB2 endpoint 1 transmittal length                         */
  __IM  uint8_t   RESERVED10;
  __IOM uint8_t   R8_U2EP1_CTRL__R8_U2H_SETUP;  /*!< (@ 0x00000026) USB2 endpoint 1 control;host aux setup                     */
  __IM  uint8_t   RESERVED11;
  __IOM uint8_t   R8_U2EP2_T_LEN_R8_U2H_EP_PID; /*!< (@ 0x00000028) USB2 endpoint 2 transmittal length;host endpoint
                                                                    and PID                                                    */
  __IM  uint8_t   RESERVED12;
  __IOM uint8_t   R8_U2EP2_CTRL_R8_U2H_RX_CTRL; /*!< (@ 0x0000002A) USB2 endpoint 2 control;host receiver endpoint
                                                                    control                                                    */
  __IM  uint8_t   RESERVED13;
  __IOM uint8_t   R8_U2EP3_T_LEN__R8_U2H_TX_LEN;/*!< (@ 0x0000002C) USB2 endpoint 3 transmittal length;host transmittal
                                                                    endpoint transmittal length                                */
  __IM  uint8_t   RESERVED14;
  __IOM uint8_t   R8_U2EP3_CTRL__R8_U2H_TX_CTRL;/*!< (@ 0x0000002E) USB2 endpoint 3 control;host transmittal endpoint
                                                                    control                                                    */
  __IM  uint8_t   RESERVED15;
  __IOM uint8_t   R8_U2EP4_T_LEN;               /*!< (@ 0x00000030) USB2 endpoint 4 transmittal length                         */
  __IM  uint8_t   RESERVED16;
  __IOM uint8_t   R8_U2EP4_CTRL;                /*!< (@ 0x00000032) USB2 endpoint 4 control                                    */
  __IM  uint8_t   RESERVED17;
  __IM  uint16_t  RESERVED18[16];
  __IOM uint16_t  R16_U2EP5_DMA;                /*!< (@ 0x00000054) USB2 endpoint 5 DMA buffer address                         */
  __IM  uint16_t  RESERVED19;
  __IOM uint16_t  R16_U2EP6_DMA;                /*!< (@ 0x00000058) USB2 endpoint 6 DMA buffer address                         */
  __IM  uint16_t  RESERVED20;
  __IOM uint16_t  R16_U2EP7_DMA;                /*!< (@ 0x0000005C) USB2 endpoint 7 DMA buffer address                         */
  __IM  uint16_t  RESERVED21[3];
  __IOM uint8_t   R8_U2EP5_T_LEN;               /*!< (@ 0x00000064) USB2 endpoint 5 transmittal length                         */
  __IM  uint8_t   RESERVED22;
  __IOM uint8_t   R8_U2EP5_CTRL;                /*!< (@ 0x00000066) USB2 endpoint 5 control                                    */
  __IM  uint8_t   RESERVED23;
  __IOM uint8_t   R8_U2EP6_T_LEN;               /*!< (@ 0x00000068) USB2 endpoint 6 transmittal length                         */
  __IM  uint8_t   RESERVED24;
  __IOM uint8_t   R8_U2EP6_CTRL;                /*!< (@ 0x0000006A) USB2 endpoint 6 control                                    */
  __IM  uint8_t   RESERVED25;
  __IOM uint8_t   R8_U2EP7_T_LEN;               /*!< (@ 0x0000006C) USB2 endpoint 7 transmittal length                         */
  __IM  uint8_t   RESERVED26;
  __IOM uint8_t   R8_U2EP7_CTRL;                /*!< (@ 0x0000006E) USB2 endpoint 7 control                                    */
  __IM  uint8_t   RESERVED27;
  __IM  uint16_t  RESERVED28;
} USB2_Type;                                    /*!< Size = 114 (0x72)                                                         */



/* =========================================================================================================================== */
/* ================                                           PFIC                                            ================ */
/* =========================================================================================================================== */


/**
  * @brief Program Fast Interrupt Controller (PFIC)
  */

typedef struct {                                /*!< (@ 0xE000E000) PFIC Structure                                             */
  __IM  uint32_t  R32_PFIC_ISR1;                /*!< (@ 0x00000000) RO,Interrupt Status Register 1                             */
  __IM  uint32_t  R32_PFIC_ISR2;                /*!< (@ 0x00000004) RO,Interrupt Status Register 2                             */
  __IM  uint32_t  RESERVED[6];
  __IM  uint32_t  R32_PFIC_IPR1;                /*!< (@ 0x00000020) RO,Interrupt Pending Register 1                            */
  __IM  uint32_t  R32_PFIC_IPR2;                /*!< (@ 0x00000024) RO,Interrupt Pending Register 2                            */
  __IM  uint32_t  RESERVED1[6];
  __IOM uint32_t  R32_PFIC_ITHRESDR;            /*!< (@ 0x00000040) RW,Interrupt Priority Register                             */
  __IM  uint32_t  RESERVED2;
  __OM  uint32_t  R32_PFIC_CFGR;                /*!< (@ 0x00000048) Interrupt Config Register                                  */
  __IM  uint32_t  R32_PFIC_GISR;                /*!< (@ 0x0000004C) Interrupt Global Register                                  */
  __IOM uint32_t  R32_PFIC_IDCFGR;              /*!< (@ 0x00000050) RW,Interrupt Fast ID Config Register                       */
  __IM  uint32_t  RESERVED3[3];
  __IOM uint32_t  R32_PFIC_FIADDRR0;            /*!< (@ 0x00000060) Interrupt 0 address Register                               */
  __IOM uint32_t  R32_PFIC_FIADDRR1;            /*!< (@ 0x00000064) Interrupt 1 address Register                               */
  __IOM uint32_t  R32_PFIC_FIADDRR2;            /*!< (@ 0x00000068) Interrupt 2 address Register                               */
  __IOM uint32_t  R32_PFIC_FIADDRR3;            /*!< (@ 0x0000006C) Interrupt 3 address Register                               */
  __IM  uint32_t  RESERVED4[36];
  __OM  uint32_t  R32_PFIC_IENR1;               /*!< (@ 0x00000100) Interrupt Setting Register                                 */
  __OM  uint32_t  R32_PFIC_IENR2;               /*!< (@ 0x00000104) Interrupt Setting Register                                 */
  __IM  uint32_t  RESERVED5[30];
  __OM  uint32_t  R32_PFIC_IRER1;               /*!< (@ 0x00000180) Interrupt Clear Register                                   */
  __OM  uint32_t  R32_PFIC_IRER2;               /*!< (@ 0x00000184) Interrupt Clear Register                                   */
  __IM  uint32_t  RESERVED6[30];
  __OM  uint32_t  R32_PFIC_IPSR1;               /*!< (@ 0x00000200) Interrupt Pending Register                                 */
  __OM  uint32_t  R32_PFIC_IPSR2;               /*!< (@ 0x00000204) Interrupt Pending Register                                 */
  __IM  uint32_t  RESERVED7[30];
  __OM  uint32_t  R32_PFIC_IPRR1;               /*!< (@ 0x00000280) Interrupt Pending Clear Register                           */
  __OM  uint32_t  R32_PFIC_IPRR2;               /*!< (@ 0x00000284) Interrupt Pending Clear Register                           */
  __IM  uint32_t  RESERVED8[30];
  __IOM uint32_t  R32_PFIC_IACTR1;              /*!< (@ 0x00000300) Interrupt ACTIVE Register                                  */
  __IOM uint32_t  R32_PFIC_IACTR2;              /*!< (@ 0x00000304) Interrupt ACTIVE Register                                  */
  __IM  uint32_t  RESERVED9[62];
  __IOM uint32_t  R32_PFIC_IPRIOR0;             /*!< (@ 0x00000400) Interrupt Priority configuration Register 0                */
  __IM  uint32_t  RESERVED10[7];
  __IOM uint32_t  R32_PFIC_IPRIOR1;             /*!< (@ 0x00000420) Interrupt Priority configuration Register 1                */
  __IM  uint32_t  RESERVED11[7];
  __IOM uint32_t  R32_PFIC_IPRIOR2;             /*!< (@ 0x00000440) Interrupt Priority configuration Register 2                */
  __IM  uint32_t  RESERVED12[7];
  __IOM uint32_t  R32_PFIC_IPRIOR3;             /*!< (@ 0x00000460) Interrupt Priority configuration Register 3                */
  __IM  uint32_t  RESERVED13[7];
  __IOM uint32_t  R32_PFIC_IPRIOR4;             /*!< (@ 0x00000480) Interrupt Priority configuration Register 4                */
  __IM  uint32_t  RESERVED14[7];
  __IOM uint32_t  R32_PFIC_IPRIOR5;             /*!< (@ 0x000004A0) Interrupt Priority configuration Register 5                */
  __IM  uint32_t  RESERVED15[7];
  __IOM uint32_t  R32_PFIC_IPRIOR6;             /*!< (@ 0x000004C0) Interrupt Priority configuration Register 6                */
  __IM  uint32_t  RESERVED16[7];
  __IOM uint32_t  R32_PFIC_IPRIOR7;             /*!< (@ 0x000004E0) Interrupt Priority configuration Register 7                */
  __IM  uint32_t  RESERVED17[7];
  __IOM uint32_t  R32_PFIC_IPRIOR8;             /*!< (@ 0x00000500) Interrupt Priority configuration Register 8                */
  __IM  uint32_t  RESERVED18[7];
  __IOM uint32_t  R32_PFIC_IPRIOR9;             /*!< (@ 0x00000520) Interrupt Priority configuration Register 9                */
  __IM  uint32_t  RESERVED19[7];
  __IOM uint32_t  R32_PFIC_IPRIOR10;            /*!< (@ 0x00000540) Interrupt Priority configuration Register 10               */
  __IM  uint32_t  RESERVED20[7];
  __IOM uint32_t  R32_PFIC_IPRIOR11;            /*!< (@ 0x00000560) Interrupt Priority configuration Register 11               */
  __IM  uint32_t  RESERVED21[7];
  __IOM uint32_t  R32_PFIC_IPRIOR12;            /*!< (@ 0x00000580) Interrupt Priority configuration Register 12               */
  __IM  uint32_t  RESERVED22[7];
  __IOM uint32_t  R32_PFIC_IPRIOR13;            /*!< (@ 0x000005A0) Interrupt Priority configuration Register 13               */
  __IM  uint32_t  RESERVED23[7];
  __IOM uint32_t  R32_PFIC_IPRIOR14;            /*!< (@ 0x000005C0) Interrupt Priority configuration Register 14               */
  __IM  uint32_t  RESERVED24[7];
  __IOM uint32_t  R32_PFIC_IPRIOR15;            /*!< (@ 0x000005E0) Interrupt Priority configuration Register 15               */
  __IM  uint32_t  RESERVED25[7];
  __IOM uint32_t  R32_PFIC_IPRIOR16;            /*!< (@ 0x00000600) Interrupt Priority configuration Register 16               */
  __IM  uint32_t  RESERVED26[7];
  __IOM uint32_t  R32_PFIC_IPRIOR17;            /*!< (@ 0x00000620) Interrupt Priority configuration Register 17               */
  __IM  uint32_t  RESERVED27[7];
  __IOM uint32_t  R32_PFIC_IPRIOR18;            /*!< (@ 0x00000640) Interrupt Priority configuration Register 18               */
  __IM  uint32_t  RESERVED28[7];
  __IOM uint32_t  R32_PFIC_IPRIOR19;            /*!< (@ 0x00000660) Interrupt Priority configuration Register 19               */
  __IM  uint32_t  RESERVED29[7];
  __IOM uint32_t  R32_PFIC_IPRIOR20;            /*!< (@ 0x00000680) Interrupt Priority configuration Register 20               */
  __IM  uint32_t  RESERVED30[7];
  __IOM uint32_t  R32_PFIC_IPRIOR21;            /*!< (@ 0x000006A0) Interrupt Priority configuration Register 21               */
  __IM  uint32_t  RESERVED31[7];
  __IOM uint32_t  R32_PFIC_IPRIOR22;            /*!< (@ 0x000006C0) Interrupt Priority configuration Register 22               */
  __IM  uint32_t  RESERVED32[7];
  __IOM uint32_t  R32_PFIC_IPRIOR23;            /*!< (@ 0x000006E0) Interrupt Priority configuration Register 23               */
  __IM  uint32_t  RESERVED33[7];
  __IOM uint32_t  R32_PFIC_IPRIOR24;            /*!< (@ 0x00000700) Interrupt Priority configuration Register 24               */
  __IM  uint32_t  RESERVED34[7];
  __IOM uint32_t  R32_PFIC_IPRIOR25;            /*!< (@ 0x00000720) Interrupt Priority configuration Register 25               */
  __IM  uint32_t  RESERVED35[7];
  __IOM uint32_t  R32_PFIC_IPRIOR26;            /*!< (@ 0x00000740) Interrupt Priority configuration Register 26               */
  __IM  uint32_t  RESERVED36[7];
  __IOM uint32_t  R32_PFIC_IPRIOR27;            /*!< (@ 0x00000760) Interrupt Priority configuration Register 27               */
  __IM  uint32_t  RESERVED37[7];
  __IOM uint32_t  R32_PFIC_IPRIOR28;            /*!< (@ 0x00000780) Interrupt Priority configuration Register 28               */
  __IM  uint32_t  RESERVED38[7];
  __IOM uint32_t  R32_PFIC_IPRIOR29;            /*!< (@ 0x000007A0) Interrupt Priority configuration Register 29               */
  __IM  uint32_t  RESERVED39[7];
  __IOM uint32_t  R32_PFIC_IPRIOR30;            /*!< (@ 0x000007C0) Interrupt Priority configuration Register 30               */
  __IM  uint32_t  RESERVED40[7];
  __IOM uint32_t  R32_PFIC_IPRIOR31;            /*!< (@ 0x000007E0) Interrupt Priority configuration Register 31               */
  __IM  uint32_t  RESERVED41[7];
  __IOM uint32_t  R32_PFIC_IPRIOR32;            /*!< (@ 0x00000800) Interrupt Priority configuration Register 32               */
  __IM  uint32_t  RESERVED42[7];
  __IOM uint32_t  R32_PFIC_IPRIOR33;            /*!< (@ 0x00000820) Interrupt Priority configuration Register 33               */
  __IM  uint32_t  RESERVED43[7];
  __IOM uint32_t  R32_PFIC_IPRIOR34;            /*!< (@ 0x00000840) Interrupt Priority configuration Register 34               */
  __IM  uint32_t  RESERVED44[7];
  __IOM uint32_t  R32_PFIC_IPRIOR35;            /*!< (@ 0x00000860) Interrupt Priority configuration Register 35               */
  __IM  uint32_t  RESERVED45[7];
  __IOM uint32_t  R32_PFIC_IPRIOR36;            /*!< (@ 0x00000880) Interrupt Priority configuration Register 36               */
  __IM  uint32_t  RESERVED46[7];
  __IOM uint32_t  R32_PFIC_IPRIOR37;            /*!< (@ 0x000008A0) Interrupt Priority configuration Register 37               */
  __IM  uint32_t  RESERVED47[7];
  __IOM uint32_t  R32_PFIC_IPRIOR38;            /*!< (@ 0x000008C0) Interrupt Priority configuration Register 38               */
  __IM  uint32_t  RESERVED48[7];
  __IOM uint32_t  R32_PFIC_IPRIOR39;            /*!< (@ 0x000008E0) Interrupt Priority configuration Register 39               */
  __IM  uint32_t  RESERVED49[7];
  __IOM uint32_t  R32_PFIC_IPRIOR40;            /*!< (@ 0x00000900) Interrupt Priority configuration Register 40               */
  __IM  uint32_t  RESERVED50[7];
  __IOM uint32_t  R32_PFIC_IPRIOR41;            /*!< (@ 0x00000920) Interrupt Priority configuration Register 41               */
  __IM  uint32_t  RESERVED51[7];
  __IOM uint32_t  R32_PFIC_IPRIOR42;            /*!< (@ 0x00000940) Interrupt Priority configuration Register 42               */
  __IM  uint32_t  RESERVED52[7];
  __IOM uint32_t  R32_PFIC_IPRIOR43;            /*!< (@ 0x00000960) Interrupt Priority configuration Register 43               */
  __IM  uint32_t  RESERVED53[7];
  __IOM uint32_t  R32_PFIC_IPRIOR44;            /*!< (@ 0x00000980) Interrupt Priority configuration Register 44               */
  __IM  uint32_t  RESERVED54[7];
  __IOM uint32_t  R32_PFIC_IPRIOR45;            /*!< (@ 0x000009A0) Interrupt Priority configuration Register 45               */
  __IM  uint32_t  RESERVED55[7];
  __IOM uint32_t  R32_PFIC_IPRIOR46;            /*!< (@ 0x000009C0) Interrupt Priority configuration Register 46               */
  __IM  uint32_t  RESERVED56[7];
  __IOM uint32_t  R32_PFIC_IPRIOR47;            /*!< (@ 0x000009E0) Interrupt Priority configuration Register 47               */
  __IM  uint32_t  RESERVED57[7];
  __IOM uint32_t  R32_PFIC_IPRIOR48;            /*!< (@ 0x00000A00) Interrupt Priority configuration Register 48               */
  __IM  uint32_t  RESERVED58[7];
  __IOM uint32_t  R32_PFIC_IPRIOR49;            /*!< (@ 0x00000A20) Interrupt Priority configuration Register 49               */
  __IM  uint32_t  RESERVED59[7];
  __IOM uint32_t  R32_PFIC_IPRIOR50;            /*!< (@ 0x00000A40) Interrupt Priority configuration Register 50               */
  __IM  uint32_t  RESERVED60[7];
  __IOM uint32_t  R32_PFIC_IPRIOR51;            /*!< (@ 0x00000A60) Interrupt Priority configuration Register 51               */
  __IM  uint32_t  RESERVED61[7];
  __IOM uint32_t  R32_PFIC_IPRIOR52;            /*!< (@ 0x00000A80) Interrupt Priority configuration Register 52               */
  __IM  uint32_t  RESERVED62[7];
  __IOM uint32_t  R32_PFIC_IPRIOR53;            /*!< (@ 0x00000AA0) Interrupt Priority configuration Register 53               */
  __IM  uint32_t  RESERVED63[11];
  __IOM uint32_t  R32_PFIC_IPRIOR54;            /*!< (@ 0x00000AD0) Interrupt Priority configuration Register 54               */
  __IM  uint32_t  RESERVED64[3];
  __IOM uint32_t  R32_PFIC_IPRIOR55;            /*!< (@ 0x00000AE0) Interrupt Priority configuration Register 55               */
  __IM  uint32_t  RESERVED65[7];
  __IOM uint32_t  R32_PFIC_IPRIOR56;            /*!< (@ 0x00000B00) Interrupt Priority configuration Register 56               */
  __IM  uint32_t  RESERVED66[7];
  __IOM uint32_t  R32_PFIC_IPRIOR57;            /*!< (@ 0x00000B20) Interrupt Priority configuration Register 57               */
  __IM  uint32_t  RESERVED67[7];
  __IOM uint32_t  R32_PFIC_IPRIOR58;            /*!< (@ 0x00000B40) Interrupt Priority configuration Register 58               */
  __IM  uint32_t  RESERVED68[7];
  __IOM uint32_t  R32_PFIC_IPRIOR59;            /*!< (@ 0x00000B60) Interrupt Priority configuration Register 59               */
  __IM  uint32_t  RESERVED69[7];
  __IOM uint32_t  R32_PFIC_IPRIOR60;            /*!< (@ 0x00000B80) Interrupt Priority configuration Register 60               */
  __IM  uint32_t  RESERVED70[7];
  __IOM uint32_t  R32_PFIC_IPRIOR61;            /*!< (@ 0x00000BA0) Interrupt Priority configuration Register 61               */
  __IM  uint32_t  RESERVED71[15];
  __IOM uint32_t  R32_PFIC_IPRIOR62;            /*!< (@ 0x00000BE0) Interrupt Priority configuration Register 62               */
  __IM  uint32_t  RESERVED72[7];
  __IOM uint32_t  R32_PFIC_IPRIOR63;            /*!< (@ 0x00000C00) Interrupt Priority configuration Register 63               */
  __IM  uint32_t  RESERVED73[67];
  __IOM uint32_t  R32_PFIC_SCTLR;               /*!< (@ 0x00000D10) System Control Register                                    */
} PFIC_Type;                                    /*!< Size = 3348 (0xd14)                                                       */



/* =========================================================================================================================== */
/* ================                                          Systick                                          ================ */
/* =========================================================================================================================== */


/**
  * @brief Systick register (Systick)
  */

typedef struct {                                /*!< (@ 0xE000F000) Systick Structure                                          */
  __IOM uint32_t  R32_STK_CTLR;                 /*!< (@ 0x00000000) Systick counter control register                           */
  __IOM uint32_t  R32_STK_SR;                   /*!< (@ 0x00000004) Systick count status register                              */
  __IOM uint32_t  R32_STK_CNTL;                 /*!< (@ 0x00000008) Systick counter low register                               */
  __IOM uint32_t  R32_STK_CNTH;                 /*!< (@ 0x0000000C) Systick counter high register                              */
  __IOM uint32_t  R32_STK_CMPLR;                /*!< (@ 0x00000010) Systick compare low register                               */
  __IOM uint32_t  R32_STK_CMPHR;                /*!< (@ 0x00000014) Systick compare high register                              */
} Systick_Type;                                 /*!< Size = 24 (0x18)                                                          */


/** @} */ /* End of group Device_Peripheral_peripherals */


/* =========================================================================================================================== */
/* ================                          Device Specific Peripheral Address Map                           ================ */
/* =========================================================================================================================== */


/** @addtogroup Device_Peripheral_peripheralAddr
  * @{
  */

#define SYS_BASE                    0x40001000UL
#define TMR0_BASE                   0x40002000UL
#define TMR1_BASE                   0x40002400UL
#define TMR2_BASE                   0x40002800UL
#define TMR3_BASE                   0x40002C00UL
#define UART0_BASE                  0x40003000UL
#define UART1_BASE                  0x40003400UL
#define UART2_BASE                  0x40003800UL
#define UART3_BASE                  0x40003C00UL
#define SPI0_BASE                   0x40004000UL
#define SPI1_BASE                   0x40004400UL
#define I2C_BASE                    0x40004800UL
#define PWMx_BASE                   0x40005000UL
#define USB_BASE                    0x40008000UL
#define USB2_BASE                   0x40008400UL
#define PFIC_BASE                   0xE000E000UL
#define Systick_BASE                0xE000F000UL

/** @} */ /* End of group Device_Peripheral_peripheralAddr */


/* =========================================================================================================================== */
/* ================                                  Peripheral declaration                                   ================ */
/* =========================================================================================================================== */


/** @addtogroup Device_Peripheral_declaration
  * @{
  */

#define SYS                         ((SYS_Type*)               SYS_BASE)
#define TMR0                        ((TMR0_Type*)              TMR0_BASE)
#define TMR1                        ((TMR1_Type*)              TMR1_BASE)
#define TMR2                        ((TMR2_Type*)              TMR2_BASE)
#define TMR3                        ((TMR3_Type*)              TMR3_BASE)
#define UART0                       ((UART0_Type*)             UART0_BASE)
#define UART1                       ((UART1_Type*)             UART1_BASE)
#define UART2                       ((UART2_Type*)             UART2_BASE)
#define UART3                       ((UART3_Type*)             UART3_BASE)
#define SPI0                        ((SPI0_Type*)              SPI0_BASE)
#define SPI1                        ((SPI1_Type*)              SPI1_BASE)
#define I2C                         ((I2C_Type*)               I2C_BASE)
#define PWMx                        ((PWMx_Type*)              PWMx_BASE)
#define USB                         ((USB_Type*)               USB_BASE)
#define USB2                        ((USB2_Type*)              USB2_BASE)
#define PFIC                        ((PFIC_Type*)              PFIC_BASE)
#define Systick                     ((Systick_Type*)           Systick_BASE)

/** @} */ /* End of group Device_Peripheral_declaration */


/* =========================================  End of section using anonymous unions  ========================================= */
#if defined (__CC_ARM)
  #pragma pop
#elif defined (__ICCARM__)
  /* leave anonymous unions enabled */
#elif defined(__ARMCC_VERSION) && (__ARMCC_VERSION >= 6010050)
  #pragma clang diagnostic pop
#elif defined (__GNUC__)
  /* anonymous unions are enabled by default */
#elif defined (__TMS470__)
  /* anonymous unions are enabled by default */
#elif defined (__TASKING__)
  #pragma warning restore
#elif defined (__CSMC__)
  /* anonymous unions are enabled by default */
#endif


#ifdef __cplusplus
}
#endif

#endif /* CH583SFR_H */


/** @} */ /* End of group CH583SFR */

/** @} */ /* End of group WCH Ltd. */
